Repository AL-GONG/Web, pull requests merged in 2022-07, with the labels that each got.

#7 #6 feat: StudyInfo page UI 구현
  src/blocks/AlignItemsList/AlignItemsList.tsx
  src/blocks/AlignItemsList/index.tsx
  src/blocks/AvatarGroup/AvatarGroup.tsx
  src/blocks/AvatarGroup/index.tsx
  src/blocks/CardGrid/CardGrid.tsx
  src/blocks/CardGrid/index.tsx
  src/blocks/SearchTextField/SearchTextField.tsx
  src/blocks/SearchTextField/index.tsx
  src/blocks/SplitButton/SplitButton.tsx
  src/blocks/SplitButton/index.tsx
  src/index.tsx
  src/pages/StudyInfo/StudyInfo.tsx
  src/pages/StudyInfo/index.tsx
  src/pages/StudyList/StudyList.tsx
  src/pages/StudyList/index.tsx
Labels: enhancement

#12 refactor: #11 block, page 단위 컴포넌트 분할
  src/blocks/AlignItemsList/AlignItemsList.tsx
  src/blocks/AlignItemsList/index.tsx
  src/blocks/AvatarGroup/AvatarGroup.tsx
  src/blocks/AvatarGroup/index.tsx
  src/blocks/CardGrid/CardGrid.tsx
  src/blocks/CardGrid/index.tsx
  src/blocks/Profile/index.tsx
  src/blocks/SearchTextField/index.tsx
  src/blocks/ShadowBox/index.tsx
  src/blocks/SplitButton/index.tsx
  src/pages/StudyInfo/SessionGrid/index.tsx
  src/pages/StudyInfo/StudyInfo.tsx
  src/pages/StudyInfo/StudyInfoHeader/index.tsx
  src/pages/StudyInfo/StudyInfoMiddleBar/SearchTextField/index.tsx
  src/pages/StudyInfo/StudyInfoMiddleBar/SortSplitButton/index.tsx
  src/pages/StudyInfo/StudyInfoMiddleBar/index.tsx
  src/pages/StudyList/StudyList.tsx
  src/pages/StudyList/StudyListItem/index.tsx
  src/pages/StudyList/index.tsx
Labels: documentation

#16 #14 feat: CodeMirror 라이브러리 연동 및 CodeViewer Block 구현
  .pnp.cjs
  .yarn/cache/@codemirror-autocomplete-npm-6.0.4-d75044a875-58c9ff81cc.zip
  .yarn/cache/@codemirror-commands-npm-6.0.1-05bce93704-7b3b73596c.zip
  .yarn/cache/@codemirror-language-npm-6.2.0-53a1ed1c50-c1ab29c7c1.zip
  .yarn/cache/@codemirror-legacy-modes-npm-6.1.0-c7bbf4c22c-bc0e3b7713.zip
  .yarn/cache/@codemirror-lint-npm-6.0.0-915d1bdcc0-e1da165ad3.zip
  .yarn/cache/@codemirror-search-npm-6.0.0-0fbd4c00e6-e40b55f1ff.zip
  .yarn/cache/@codemirror-state-npm-6.1.0-fbfc32911b-5185df31f2.zip
  .yarn/cache/@codemirror-theme-one-dark-npm-6.0.0-e5626890f8-916f23e3ce.zip
  .yarn/cache/@codemirror-view-npm-6.0.3-daf186b139-30b56d2afa.zip
  .yarn/cache/@lezer-common-npm-1.0.0-2b393671a9-0ba652b39f.zip
  .yarn/cache/@lezer-highlight-npm-1.0.0-ffceff70f6-9ce6c4ea04.zip
  .yarn/cache/@lezer-lr-npm-1.2.0-462701b40d-6fda874083.zip
  .yarn/cache/@uiw-react-codemirror-npm-4.11.1-c3dcd5c814-c4216398fd.zip
  .yarn/cache/codemirror-npm-6.0.1-a317bb67bb-1a78f7077a.zip
  .yarn/cache/crelt-npm-1.0.5-6dad646a54-04a618c587.zip
  .yarn/cache/style-mod-npm-4.0.0-dffb5d3925-c19f73d660.zip
  .yarn/cache/w3c-keyname-npm-2.2.4-8c6e5969c5-890180452b.zip
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/eslint/lib/api.js
  .yarn/sdks/eslint/package.json
  .yarnrc.yml
  package.json
  src/blocks/CodeViewer/CodeViewer.tsx
  src/blocks/CodeViewer/index.tsx
  yarn.lock
Labels: enhancement

#19 Auth 기능
  src/App.tsx
  src/api/index.ts
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/index.tsx
  src/hoc/AuthContext/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/LoginWidget/index.tsx
  src/pages/Login/index.tsx
  src/templates/PageTemplate/index.tsx
  src/utils/http.ts
Labels: enhancement

#22 Solution 페이지
  .pnp.cjs
  .yarn/cache/@types-react-syntax-highlighter-npm-15.5.3-7c06005201-0aaf7af216.zip
  package.json
  src/App.tsx
  src/blocks/CodeViewer/CodeViewer.tsx
  src/blocks/CodeViewer/index.tsx
  src/blocks/MarkdownViewer/MarkdownViewer.tsx
  src/blocks/MarkdownViewer/index.tsx
  src/components/TextEditor/TextEditor.tsx
  src/components/TextEditor/index.tsx
  src/hooks/useView.ts
  src/pages/Session/SessionHeader/index.tsx
  src/pages/Solution/Solution.tsx
  src/pages/Solution/SolutionForm/SolutionForm.tsx
  src/pages/Solution/SolutionForm/index.tsx
  src/pages/Solution/SolutionHeader/index.tsx
  src/pages/Solution/index.tsx
  src/types/react-syntax-highlighter/index.d.ts
  yarn.lock
Labels: enhancement, refactor

#25 feat: #23 스터디 목록 조회 API 연동 및 스터디 버튼 구현
  src/App.tsx
  src/api/index.ts
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/StudyButton/CreateStudyButton/index.tsx
  src/components/Navbar/StudyButton/index.tsx
  src/components/Navbar/index.tsx
  src/pages/StudyList/StudyList.tsx
  src/pages/StudyList/StudyListItem/index.tsx
  src/pages/StudyList/index.tsx
Labels: enhancement

#28 issue-8 session/모킹을 위한 환경 구성
  package.json
  public/mockServiceWorker.js
  src/index.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/renderWithRouterMatch.tsx
  src/mocks/server.ts
  src/pages/Session/Problem/index.tsx
  src/pages/Session/Session.tsx
  src/pages/Session/SessionHeader/index.test.tsx
  src/pages/Session/SessionHeader/index.tsx
  src/pages/Session/index.test.tsx
  src/pages/Session/index.tsx
  src/setupTests.ts
  src/utils/formatDateLabel.ts
  src/utils/http.ts
  tsconfig.json
Labels: enhancement

#30 issue-8 Session/유저 리뷰 UI 구현
  .pnp.cjs
  .yarn/cache/react-card-flip-npm-1.1.5-161e9b1996-f46711bed0.zip
  package.json
  src/components/atoms/Button/index.tsx
  src/components/blocks/Header/index.tsx
  src/components/blocks/Navbar/LoginButton/index.tsx
  src/components/pages/Session/ProblemAdder/ProblemAdder.tsx
  src/components/pages/Session/ProblemCard/index.tsx
  src/components/pages/Session/ProblemList/index.tsx
  src/components/pages/Session/SessionHeader/index.tsx
  src/components/pages/StudyInfo/StudyInfoMiddleBar/SessionAdder/index.tsx
  src/components/pages/StudyInfo/StudyInfoMiddleBar/SortSplitButton/index.tsx
  src/hoc/Layout/index.tsx
  yarn.lock
Labels: enhancement

#33 issue-31 test/REST GET mocking 추가
  src/App.tsx
  src/components/atoms/Button/index.tsx
  src/components/blocks/Navbar/LoginButton/index.tsx
  src/components/blocks/Navbar/StudyButton/CreateStudyButton/index.tsx
  src/components/blocks/Navbar/StudyButton/index.tsx
  src/components/blocks/Navbar/index.tsx
  src/components/blocks/TextEditor/MarkdownViewer/index.tsx
  src/components/blocks/TextEditor/TextEditor.tsx
  src/components/pages/Session/index.test.tsx
  src/mocks/handlers.ts
Labels: enhancement, refactor

#35 issue-8 refactor/React query 사용
  src/api/index.ts
  src/components/pages/Session/ProblemCard/index.tsx
  src/components/pages/Session/ProblemLabel/index.tsx
  src/components/pages/Session/ProblemList/index.tsx
  src/components/pages/Session/Session.tsx
  src/components/pages/Session/SessionHeader/index.tsx
  src/components/pages/Session/index.tsx
Labels: refactor

#36 issue-8 Session/필요한 정보 fetch
  src/api/index.ts
  src/components/blocks/Navbar/Navbar.tsx
  src/components/blocks/Navbar/index.tsx
  src/components/blocks/Profile/index.tsx
  src/components/blocks/Wrapper/index.tsx
  src/components/pages/Session/ProblemCard/index.tsx
  src/components/pages/Session/Session.tsx
  src/components/pages/Session/index.tsx
  src/components/pages/Solution/SolutionHeader/index.tsx
  src/components/pages/StudyInfo/StudyInfoHeader/index.tsx
  src/hoc/ColorModeContext/index.tsx
  src/hoc/Layout/index.tsx
  src/mocks/handlers.ts
Labels: enhancement

#39 feat: #26 스터티 생성 API 구현
  src/api/index.ts
  src/components/blocks/Navbar/StudyButton/CreateStudyButton/CreateStudyButton.tsx
  src/components/blocks/Navbar/StudyButton/CreateStudyButton/index.tsx
Labels: enhancement

#42 feat #40 스터디 생성 유효성 검사 및 예외 처리
  src/components/blocks/Navbar/StudyButton/CreateStudyButton/CreateStudyButton.tsx
  src/components/blocks/Navbar/StudyButton/CreateStudyButton/index.tsx
  src/components/blocks/ShadowBox/index.tsx
Labels: enhancement, refactor

#45 feat #43 디바운스 util 함수 구현 및 적용
  src/components/blocks/Navbar/StudyButton/CreateStudyButton/CreateStudyButton.tsx
  src/components/blocks/Navbar/StudyButton/CreateStudyButton/index.tsx
  src/utils/debounce.ts
Labels: enhancement

#46 feat #44 Modal Block 구현 및 스터디 생성 완료 navigate 구현
  src/components/blocks/Modal/index.tsx
  src/components/blocks/Navbar/StudyButton/CreateStudyButton/CreateStudyButton.tsx
  src/components/blocks/Navbar/StudyButton/CreateStudyButton/index.tsx
Labels: enhancement

#47 issue-8 Session/세션 정보 수정
  src/App.tsx
  src/api/index.ts
  src/components/atoms/DateLabel/index.tsx
  src/components/pages/Session/ProblemCard/index.tsx
  src/components/pages/Session/Session.tsx
  src/components/pages/Session/SessionHeader/SessionEditor/index.tsx
  src/components/pages/Session/SessionHeader/index.tsx
  src/components/pages/Study/SessionGrid/index.tsx
  src/components/pages/Study/StudyMiddleBar/SessionAdder/index.tsx
  src/mocks/handlers/session.js
  src/utils/formatDateLabel.ts
  src/utils/http.ts
Labels: enhancement

#49 issue-8 Session/세션 삭제 기능
  src/api/index.ts
  src/components/pages/Session/SessionHeader/index.tsx
  src/mocks/handlers/session.js
  src/mocks/handlers/study.js
  src/utils/formatDateLabel.ts
  src/utils/http.ts
Labels: enhancement
